apiVersion: v1
kind: Secret
metadata:
  name: dockerhub
  namespace: {{ .Release.Name }}-management
  labels:
    app.kubernetes.io/name: kube-ctf
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
data:
  .dockerconfigjson: {{ .Values.dockerSecret }}
type: kubernetes.io/dockerconfigjson