apiVersion: v1
kind: Secret
metadata:
  name: dockerhub
  namespace: ctfd
  labels:
    app.kubernetes.io/managed-by: Helm
data:
  .dockerconfigjson: {{ .Values.dockerSecret }}
type: kubernetes.io/dockerconfigjson
